[2025-07-28T17:18:55.748+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: jobs_ingest_transform.t2_transform manual__2025-07-28T16:54:34.187368+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
